AWSTemplateFormatVersion: "2010-09-09"
Description: LAMP Stack on Amazon Linux 2023 (EC2 + Apache + PHP + MariaDB)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type

  DBRootPassword:
    Type: String
    Default: kampli00
    Description: mysql DB root password
Resources:
  LampSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${AWS::StackName}-SecurityGroup"
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  LampInstance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages:
            dnf:
              httpd: []
              wget: []
              php: []
              php-fpm: []
              php-mysqlnd: []
              php-mysqli: []
              php-json: []
              php-devel: []
              mariadb105-server: []
              openssl: []
              mod_ssl: []

          files:
            /var/www/html/index.php:
              owner: apache
              group: apache
              mode: "0644"
              content: |
                <?php
                phpinfo();
                ?>

          commands:
            01_permissions:
              command: |
                usermod -a -G apache ec2-user || true
                chown -R apache:apache /var/www
                find /var/www -type d -exec chmod 2755 {} \;
                find /var/www -type f -exec chmod 0644 {} \;

            02_start_services:
              command: |
                systemctl enable httpd mariadb
                systemctl start mariadb
                until mysqladmin ping --silent; do sleep 2; done

            03_secure_mariadb:
              command: !Sub |
                mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}'; FLUSH PRIVILEGES;"
                mysql -u root --password=${DBRootPassword} -e "
                DELETE FROM mysql.user WHERE User='';
                DROP DATABASE IF EXISTS test;
                FLUSH PRIVILEGES;
                "

            04_generate_self_signed_cert:
              command: |
                CERT=/etc/pki/tls/certs/apache-selfsigned.crt
                KEY=/etc/pki/tls/private/apache-selfsigned.key

                if [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
                  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                    -keyout $KEY \
                    -out $CERT \
                    -subj "/C=GB/ST=Scotland/L=Glasgow/O=KampliLimited/OU=IT/CN=kamplidev.com/emailAddress=kampli@gmail.com"
                  chmod 600 $KEY
                fi

            05_configure_apache_ssl:
              command: |
                SSL_CONF=/etc/httpd/conf.d/ssl.conf

                sed -i \
                  -e 's|^SSLCertificateFile .*|SSLCertificateFile /etc/pki/tls/certs/apache-selfsigned.crt|' \
                  -e 's|^SSLCertificateKeyFile .*|SSLCertificateKeyFile /etc/pki/tls/private/apache-selfsigned.key|' \
                  $SSL_CONF

            06_restart_httpd:
              command: |
                systemctl restart httpd

          services:
            systemd:
              httpd:
                enabled: true
                ensureRunning: true
              mariadb:
                enabled: true
                ensureRunning: true

    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      SecurityGroupIds:
        - !Ref LampSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-LampServer_EC2"

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          dnf install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init \
            --stack ${AWS::StackName} \
            --resource LampInstance \
            --region ${AWS::Region}

          /opt/aws/bin/cfn-signal \
            --exit-code $? \
            --stack ${AWS::StackName} \
            --resource LampInstance \
            --region ${AWS::Region}


Outputs:
  InstancePublicIP:
    Description: Public IP address of the LAMP EC2 instance
    Value: !GetAtt LampInstance.PublicIp
  PublicDNS:
    Description: Public DNS of the LAMP Stack EC2
    Value: !GetAtt "LampInstance.PublicDnsName"
  InstanceName:
    Description: Name of the LAMP EC2 instance
    Value: !Sub "${AWS::StackName}-LampServer_EC2"
  WebsiteURL:
    Description: URL of the LAMP Stack
    Value: !Sub "http://${LampInstance.PublicDnsName}"
