AWSTemplateFormatVersion: "2010-09-09"
Description: LAMP Stack on Amazon Linux 2023 (EC2 + Apache + PHP + MariaDB)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type

  DBRootPassword:
    Type: String
    Default: kampli00
    Description: mysql DB root password
Resources:
  LampSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  LampInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      SecurityGroupIds:
        - !Ref LampSecurityGroup
      Tags:
        - Value: !Sub "${AWS::StackName}-LampServer_EC2"
          Key: Name
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -x
          LOG_FILE="/var/log/$(date +'%Y%m%d%H%M%S')_UserData_Script_output.log"
          #mkdir -p /var/log
          touch $LOG_FILE
          exec 1>$LOG_FILE
          exec 2>&1
          chmod 777 $LOG_FILE
          echo "logging output to $LOG_FILE"
          i=0;
          echo "kampli - $((i++)) - start"
          echo "kampli - $((i++)) - after log"
          echo "kampli - $((i++)) - after log setup"
          dnf update -y

          # Install LAMP packages
          dnf install -y httpd wget php-fpm php-mysqlnd php-mysqli php-json php php-devel
          dnf install -y mariadb105-server

          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www

          # Enable and start services
          systemctl enable httpd mariadb
          systemctl start httpd mariadb

          # Set permissions
          chown -R apache:apache /var/www
          chmod 2775 /var/www && find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;

          echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
          chmod -R 755 /var/www

          # Create test PHP page
          cat << 'EOF' > /var/www/html/index.php
          <?php
          phpinfo();
          ?>
          EOF

          mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}'; FLUSH PRIVILEGES;"
          mysql -u root --password=${DBRootPassword} -e "
          DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
          SELECT Host FROM mysql.user WHERE User='root';
          DELETE FROM mysql.user WHERE User='';
          DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
          DROP DATABASE IF EXISTS test;
          DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
          FLUSH PRIVILEGES;
          "
          dnf install -y openssl mod_ssl
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                      -keyout /etc/pki/tls/private/apache-selfsigned.key \
                      -out /etc/pki/tls/certs/apache-selfsigned.crt \
                      -subj "/C=GB/ST=Scotland/L=Glasgow/O=KampliLimited/OU=IT/CN=kamplidev.com/emailAddress=kampli@gmail.com"
          
          # mysql_secure_installation --password=kampli00
          sslConfFile=/etc/httpd/conf.d/ssl.conf
          sed -r 's/^SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt/\#SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt\nSSLCertificateFile \/etc\/pki\/tls\/certs\/apache-selfsigned.crt/g' \
                      $sslConfFile | grep SSLCertificateFile

          sed -i -r 's/^SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt/\#SSLCertificateFile \/etc\/pki\/tls\/certs\/localhost.crt\nSSLCertificateFile \/etc\/pki\/tls\/certs\/apache-selfsigned.crt/g' \
                      $sslConfFile | grep SSLCertificateFile

          grep SSLCertificateFile $sslConfFile

          sslConfFile=/etc/httpd/conf.d/ssl.conf
          sed -r 's/^SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key/\#SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key\nSSLCertificateKeyFile \/etc\/pki\/tls\/private\/apache-selfsigned.key/g' \
                      $sslConfFile | grep SSLCertificateKeyFile
          sed -i -r 's/^SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key/\#SSLCertificateKeyFile \/etc\/pki\/tls\/private\/localhost.key\nSSLCertificateKeyFile \/etc\/pki\/tls\/private\/apache-selfsigned.key/g' \
                      $sslConfFile | grep SSLCertificateKeyFile
          grep SSLCertificateKeyFile $sslConfFile
          systemctl restart httpd

Outputs:
  InstancePublicIP:
    Description: Public IP address of the LAMP EC2 instance
    Value: !GetAtt LampInstance.PublicIp
  PublicDNS:
    Description: Public DNS of the LAMP Stack EC2
    Value: !GetAtt "LampInstance.PublicDnsName"
  WebsiteURL:
    Description: URL of the LAMP Stack
    Value: !Sub "http://${LampInstance.PublicDnsName}"
