AWSTemplateFormatVersion: "2010-09-09"
Description: LAMP Stack on Amazon Linux 2023 (EC2 + Apache + PHP + MariaDB)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
    Description: EC2 instance type

  DBRootPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Default: rootkampli00
    Description: mysql DB root password
  
  WordPressDBName:
    Type: String
    Default: wordpressdb

  WordPressDBUser:
    Type: String
    Default: wpuser

  WordPressDBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Default: wpkampli00

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDRs:
    Type: CommaDelimitedList
    Default: 10.0.1.0/24,10.0.2.0/24,10.0.3.0/24

  PrivateSubnetCIDRs:
    Type: CommaDelimitedList
    Default: 10.0.101.0/24,10.0.102.0/24,10.0.103.0/24

Resources:

  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value: "LAMP Stack - VPC"

  PublicSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [0, !Ref PublicSubnetCIDRs]
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Public Subnet AZ A"
      AvailabilityZone:
        Fn::Select:
          - "0"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  PublicSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [1, !Ref PublicSubnetCIDRs]
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Public Subnet AZ B"
      AvailabilityZone:
        Fn::Select:
          - "1"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  PublicSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [2, !Ref PublicSubnetCIDRs]
      MapPublicIpOnLaunch: true
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Public Subnet AZ C"
      AvailabilityZone:
        Fn::Select:
          - "2"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  PrivateSubnet1:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [0, !Ref PrivateSubnetCIDRs]
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Subnet AZ A"
      AvailabilityZone:
        Fn::Select:
          - "0"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [1, !Ref PrivateSubnetCIDRs]
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Subnet AZ B"
      AvailabilityZone:
        Fn::Select:
          - "1"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  PrivateSubnet3:
    Type: "AWS::EC2::Subnet"
    Properties:
      CidrBlock: !Select [2, !Ref PrivateSubnetCIDRs]
      MapPublicIpOnLaunch: false
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Subnet AZ C"
      AvailabilityZone:
        Fn::Select:
          - "2"
          - Fn::GetAZs:
              Ref: "AWS::Region"

  RouteTablePublic:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Public Route Table"

  RouteTablePublicAssociation1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePublic"
      SubnetId:
        Ref: "PublicSubnet1"

  RouteTablePublicAssociation2:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePublic"
      SubnetId:
        Ref: "PublicSubnet2"

  RouteTablePublicAssociation3:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePublic"
      SubnetId:
        Ref: "PublicSubnet3"

  RouteTablePublicRoute0:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:
        Ref: "RouteTablePublic"
      GatewayId:
        Ref: "Igw"

  RouteTablePrivate1:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Route Table A"

  RouteTablePrivate1Association1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePrivate1"
      SubnetId:
        Ref: "PrivateSubnet1"

  RouteTablePrivate1Route0:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:
        Ref: "RouteTablePrivate1"
      NatGatewayId:
        Ref: "NatGw1"

  RouteTablePrivate2:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Route Table B"

  RouteTablePrivate2Association1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePrivate2"
      SubnetId:
        Ref: "PrivateSubnet2"

  RouteTablePrivate2Route0:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:
        Ref: "RouteTablePrivate2"
      NatGatewayId:
        Ref: "NatGw1"

  RouteTablePrivate3:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId:
        Ref: "VPC"
      Tags:
        - Key: "Name"
          Value: "Private Route Table C"

  RouteTablePrivate3Association1:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      RouteTableId:
        Ref: "RouteTablePrivate3"
      SubnetId:
        Ref: "PrivateSubnet3"

  RouteTablePrivate3Route0:
    Type: "AWS::EC2::Route"
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      RouteTableId:
        Ref: "RouteTablePrivate3"
      NatGatewayId:
        Ref: "NatGw1"

  Igw:
    Type: "AWS::EC2::InternetGateway"
    Properties: { }

  IGWAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Ref: "VPC"
      InternetGatewayId:
        Ref: "Igw"

  NatGw1:
    Type: "AWS::EC2::NatGateway"
    Properties:
      SubnetId:
        Ref: "PublicSubnet1"
      AllocationId:
        Fn::GetAtt:
          - "NatGw1ElasticIP"
          - "AllocationId"
      Tags:
        - Key: "Name"
          Value: "NAT GW A"

  NatGw1ElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
      Tags:
        - Key: "Name"
          Value: "NAT GW EIP"

  SystemsManagerEC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LAMP-SystemsManagerEC2Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: SystemsManagerEC2Role

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: LAMP-SystemsManagerEC2Profile
      Roles:
        - !Ref SystemsManagerEC2Role


  ### Security Group ###
  PrivateInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow HTTP from ALB or Bastion
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/16

  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable HTTP access from internet
      GroupName: AllowHttpFromEverywhere
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0



  Ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Enable HTTP access from within VPC
      GroupName: AllowHttpFromALB
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          SourceSecurityGroupId: !Ref AlbSecurityGroup

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: LAMP-ApplicationLoadBalancer
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: WebServer-tg
      VpcId: !Ref VPC
      Port: 80
      Protocol: HTTP
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 200-399
      Targets:
        - Id: !Ref LampInstance
          Port: 80


  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # LampSecurityGroup:
  #   Type: AWS::EC2::SecurityGroup
  #   Properties:
  #     GroupName: !Sub "${AWS::StackName}-SecurityGroup"
  #     GroupDescription: Allow SSH and HTTP access
  #     SecurityGroupIngress:
  #       - IpProtocol: tcp
  #         FromPort: 22
  #         ToPort: 22
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 80
  #         ToPort: 80
  #         CidrIp: 0.0.0.0/0
  #       - IpProtocol: tcp
  #         FromPort: 443
  #         ToPort: 443
  #         CidrIp: 0.0.0.0/0

  LampInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT30M
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - install
            - configure
            - cfn-hup
        install:
          packages:
            yum:
              httpd: []
              wget: []
              # php: []
              # php-fpm: []
              # php-mysqlnd: []
              # php-mysqli: []
              # php-devel: []
              # php-gd: []
              # php-json: []
              mariadb105-server: []
              openssl: []
              mod_ssl: []
              stress: []

        configure:
          commands:
            01_permissions:
              command: |
                
                #TODO check why the packages are not installed via config:packages:dnf
                #dnf isnt supported by packages, though not sure why aws wouldn't throw an error, 
                # but very well throws errors for any issues with yum install.
                # yum install is flaky given the repo isnt accessible though user data runs before the install.
                # yum update has been included in the user data.
                dnf upgrade -y
                dnf install -y httpd wget php php-fpm php-mysqlnd php-mysqli php-json php-devel php-gd mariadb105-server openssl mod_ssl stress
                  
                WEB_ROOT="/var/www/html"
                INDEX_FILE="$WEB_ROOT/index.php"

                # Ensure web root exists
                mkdir -p "$WEB_ROOT"

                # Create index.php only if it does not exist
                if [ ! -f "$INDEX_FILE" ]; then
                  echo '<?php phpinfo(); ?>' > "$INDEX_FILE"
                fi

                # Fix ownership and permissions
                chown apache:apache "$INDEX_FILE"
                chmod 644 "$INDEX_FILE"
                
                usermod -a -G apache ec2-user || true
                chown -R apache:apache /var/www
                find /var/www -type d -exec chmod 755 {} \;
                find /var/www -type f -exec chmod 644 {} \;

            02_start_services:
              command: |
                systemctl enable httpd mariadb
                systemctl start mariadb
                until mysqladmin ping --silent; do sleep 2; done

            03_secure_mariadb:
              command: !Sub |
                #!/bin/bash
                set -e

                # Wait for MariaDB
                until mysqladmin ping --silent; do
                  sleep 2
                done

                # Determine how to connect as root
                if mysql -u root -e "SELECT 1" >/dev/null 2>&1; then
                  MYSQL="mysql -u root"
                elif mysql -u root -p"${DBRootPassword}" -e "SELECT 1" >/dev/null 2>&1; then
                  MYSQL="mysql -u root -p${DBRootPassword}"
                else
                  echo "ERROR: Unable to authenticate to MariaDB as root"
                  exit 1
                fi

                # Check if password already matches (idempotent)
                PASSWORD_OK=$($MYSQL -Nse "
                  SELECT COUNT(*) FROM mysql.user
                  WHERE User='root'
                    AND Host='localhost'
                    AND authentication_string = PASSWORD('${DBRootPassword}');
                ")

                if [ "$PASSWORD_OK" -eq 0 ]; then
                  echo "Setting MariaDB root password"
                  $MYSQL -e "
                    ALTER USER 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}';
                    FLUSH PRIVILEGES;
                  "
                else
                  echo "MariaDB root password already set — skipping"
                fi

                
                #mysql -e "ALTER USER IF EXISTS 'root'@'localhost' IDENTIFIED BY '${DBRootPassword}'; FLUSH PRIVILEGES;"
                mysql -u root --password=${DBRootPassword} -e "
                  DELETE FROM mysql.user WHERE User='';
                  DROP DATABASE IF EXISTS test;
                  FLUSH PRIVILEGES;
                "

            04_create_wordpress_db:
              command: !Sub |
                mysql -u root --password=${DBRootPassword} -e "
                  CREATE DATABASE IF NOT EXISTS ${WordPressDBName};
                  CREATE USER IF NOT EXISTS '${WordPressDBUser}'@'localhost'
                    IDENTIFIED BY '${WordPressDBPassword}';
                  GRANT ALL PRIVILEGES ON ${WordPressDBName}.* TO '${WordPressDBUser}'@'localhost';
                  FLUSH PRIVILEGES;
                "

            05_install_wordpress:
              command: |
                cd /tmp
                if [ ! -d /var/www/html/wp-admin ]; then
                  wget https://wordpress.org/latest.tar.gz
                  tar -xzf latest.tar.gz
                  cp -r wordpress/* /var/www/html/
                fi

            06_configure_wp:
              command: !Sub |
                cd /var/www/html
                if [ ! -f wp-config.php ]; then
                  cp wp-config-sample.php wp-config.php
                  sed -i "s/database_name_here/${WordPressDBName}/" wp-config.php
                  sed -i "s/username_here/${WordPressDBUser}/" wp-config.php
                  sed -i "s/password_here/${WordPressDBPassword}/" wp-config.php

                  curl -s https://api.wordpress.org/secret-key/1.1/salt/ >> wp-config.php
                fi

            07_fix_wp_permissions:
              command: |
                chown -R apache:apache /var/www/html
                find /var/www/html -type d -exec chmod 755 {} \;
                find /var/www/html -type f -exec chmod 644 {} \;

            08_generate_self_signed_cert:
              command: |
                CERT=/etc/pki/tls/certs/apache-selfsigned.crt
                KEY=/etc/pki/tls/private/apache-selfsigned.key

                if [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then

                  openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
                    -keyout $KEY \
                    -out $CERT \
                    -subj "/C=GB/ST=Scotland/L=Glasgow/O=KampliLimited/OU=IT/CN=kamplidev.com/emailAddress=kampli@gmail.com"
                fi

            09_configure_ssl:
              command: |
                SSL_CONF=/etc/httpd/conf.d/ssl.conf
                sed -i \
                  -e 's|^SSLCertificateFile .*|SSLCertificateFile /etc/pki/tls/certs/apache-selfsigned.crt|' \
                  -e 's|^SSLCertificateKeyFile .*|SSLCertificateKeyFile /etc/pki/tls/private/apache-selfsigned.key|' \
                  $SSL_CONF

            10_restart_httpd:
              command: |
                testFileName=/var/log/$(date +'%Y%m%d%H%M%S')_touchfile.log
                touch $testFileName
                chmod 777 $testFileName

                systemctl restart httpd

          services:
            systemd:
              httpd:
                enabled: true
                ensureRunning: true
              mariadb:
                enabled: true
                ensureRunning: true

        cfn-hup:
          files:
            /etc/cfn/cfn-hup.conf:
              mode: "0400"
              owner: root
              group: root
              content: !Sub |
                [main]
                stack=${AWS::StackId}
                region=${AWS::Region}
                interval=5

            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              mode: "0400"
              owner: root
              group: root
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.LampInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init \
                  --stack ${AWS::StackName} \
                  --resource LampInstance \
                  --region ${AWS::Region} \
                  --configsets default
                runas=root

          services:
            systemd:
              cfn-hup:
                enabled: true
                ensureRunning: true

    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PrivateSubnet1
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      SecurityGroupIds:
        # - !Ref LampSecurityGroup
        - !Ref PrivateInstanceSG
        - !Ref Ec2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}_private-subnet-EC2"

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum clean all
          yum update -y

          
          dnf install -y aws-cfn-bootstrap

          /opt/aws/bin/cfn-init \
            --stack ${AWS::StackName} \
            --resource LampInstance \
            --region ${AWS::Region} \
            --configsets default

          INIT_EXIT_CODE=$?

          /opt/aws/bin/cfn-signal \
            --exit-code $INIT_EXIT_CODE \
            --stack ${AWS::StackName} \
            --resource LampInstance \
            --region ${AWS::Region}
          
          exit $INIT_EXIT_CODE

Outputs:
  InstancePublicIP:
    Description: Public IP address of the LAMP EC2 instance
    # Value: !GetAtt LampInstance.PublicIp
    Value: !GetAtt LampInstance.PrivateIp

  PublicDNS:
    Description: Public DNS of the LAMP Stack EC2
    # Value: !GetAtt LampInstance.PublicDnsName
    Value: !GetAtt LampInstance.PrivateDnsName

  InstanceName:
    Description: Name of the LAMP EC2 instance
    Value: !Sub "${AWS::StackName}_private-subnet-EC2"

  WebsiteURL:
    Description: URL of the LAMP Stack
    # Value: !Sub "http://${LampInstance.PublicDnsName}"
    # Value: !Sub "http://${NatGw1ElasticIP.PublicIp}"
    Value: !Sub "http://${ApplicationLoadBalancer.DNSName}"
    

