AWSTemplateFormatVersion: "2010-09-09"
Description: ALB - LAMP compute

Parameters:
  Version:
    Type: String
    Default: "1"
  Environment:
    Type: String
    Default: dev

  PymysqlLayer:
    Type: String
    Description: PymysqlLayer

  LambdaArtifactsS3BucketName:
    Type: String
    Default: lamp-lambda-artifacts-725673811658-eu-west-2
    Description: "Existing bucket name or new bucket name"
  
  HttpsListener:
    Type: String
    Description: HttpsListener
  
  ALBFullName:
    Type: String
    Description: ALBFullName

    
Resources:

  AutoStartStopLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AutoStartStopPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeInstances
                  - ec2:StartInstances
                  - ec2:StopInstances
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:UpdateAutoScalingGroup
                Resource: "*"

  AutoStopLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AutoStopLambda
      Description: !Sub "AutoStopLambda version ${Version}"
      Runtime: python3.11
      Handler: lambda_autostop.handler
      Role: !GetAtt AutoStartStopLambdaRole.Arn
      Timeout: 60
      Layers:
        - !Ref PymysqlLayer
      Code:
        S3Bucket: !Ref LambdaArtifactsS3BucketName
        S3Key: lambda.zip


  AutoStopRule:
    Type: AWS::Events::Rule
    Properties:
      Name: AutoStoptRule
      Description: stop non-prod resources in the evening
      ScheduleExpression: cron(0 19 ? * MON-FRI *)
      Targets:
        - Arn: !GetAtt AutoStopLambda.Arn
          Id: AutoStopTarget

  AutoStopLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoStopLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AutoStopRule.Arn


  AutoStartLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AutoStartLambda
      Description: !Sub "AutoStartLambda version ${Version}"
      Runtime: python3.11
      Handler: lambda_autostart.handler
      Role: !GetAtt AutoStartStopLambdaRole.Arn
      Timeout: 60
      Layers:
        - !Ref PymysqlLayer
      Code:
        S3Bucket: !Ref LambdaArtifactsS3BucketName
        S3Key: lambda.zip


  AutoStartRule:
    Type: AWS::Events::Rule
    Properties:
      Name: AutoStartRule
      Description: Start non-prod resources in the morning
      ScheduleExpression: cron(0 8 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt AutoStartLambda.Arn
          Id: AutoStartLambdaTarget


  AutoStartLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoStartLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt AutoStartRule.Arn


  WakeAutoScalingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WakeAutoScalingLambda
      Description: !Sub "WakeAutoScalingLambda version ${Version}"
      Runtime: python3.11
      Handler: lambda_auto_asgwake.handler
      Role: !GetAtt AutoStartStopLambdaRole.Arn
      Timeout: 60
      Layers:
        - !Ref PymysqlLayer
      Code:
        S3Bucket: !Ref LambdaArtifactsS3BucketName
        S3Key: lambda.zip


  WakeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WakeAutoScalingLambda
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com


  WakeLambdaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: lambda
      HealthCheckEnabled: false
      Targets:
      - Id: !GetAtt WakeAutoScalingLambda.Arn

  WakeLambdaListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpsListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          PathPatternConfig:
            Values:
              - "/_wake/*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref WakeLambdaTargetGroup

  SleepAutoScalingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SleepAutoScalingLambda
      Description: !Sub "SleepAutoScalingLambda version ${Version}"
      Runtime: python3.11
      Handler: lambda_auto_asg_sleep.handler
      Role: !GetAtt AutoStartStopLambdaRole.Arn
      Timeout: 60
      Layers:
        - !Ref PymysqlLayer
      Code:
        S3Bucket: !Ref LambdaArtifactsS3BucketName
        S3Key: lambda.zip


  IdleRequestAlarm:
    Type: AWS::CloudWatch::Alarm
    # DependsOn: IdleStopLambdaPermission
    Properties:
      AlarmDescription: Stop ASG when idle
      Namespace: AWS/ApplicationELB
      MetricName: RequestCount
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBFullName
          # Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
      Statistic: Sum
      Period: 120
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      TreatMissingData: breaching
      AlarmActions:
        - !GetAtt SleepAutoScalingLambda.Arn


  IdleStopLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SleepAutoScalingLambda
      Action: lambda:InvokeFunction
      Principal: lambda.alarms.cloudwatch.amazonaws.com
      SourceArn: !GetAtt IdleRequestAlarm.Arn



  AutoRefreshLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AutoRefreshLambda
      Description: !Sub "AutoRefreshLambda version ${Version}"
      Runtime: python3.11
      Handler: lambda_auto_refresh.handler
      Role: !GetAtt AutoStartStopLambdaRole.Arn
      Timeout: 60
      Layers:
        - !Ref PymysqlLayer
      Code:
        S3Bucket: !Ref LambdaArtifactsS3BucketName
        S3Key: lambda.zip



  ImageBuilderEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ImageBuilderEventRule-2
      Description: Trigger AutoStopLambda when Image Builder AMI is AVAILABLE
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - aws.imagebuilder
        detail-type:
          - EC2 Image Builder Image State Change
        detail:
          previous-state:
            status:
              # - INTEGRATING
              - CREATING
          state:
            status:
              - BUILDING
              # - AVAILABLE
      Targets:
        - Id: AutoRefreshLambdaTarget
          Arn: !GetAtt AutoRefreshLambda.Arn



  AutoRefreshLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoRefreshLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ImageBuilderEventRule.Arn


  ImageBuilderEventLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/events/imagebuilder
      RetentionInDays: 14


  ImageBuilderEventsToCWRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowWriteToCloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt ImageBuilderEventLogGroup.Arn

  ImageBuilderAllEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ImageBuilder-All-Events
      Description: Log all AWS Image Builder events to CloudWatch
      EventBusName: default
      State: ENABLED
      EventPattern:
        source:
          - aws.imagebuilder
      Targets:
        - Id: ImageBuilderLogsTarget
          Arn: !GetAtt ImageBuilderEventLogGroup.Arn

  ImageBuilderLogsResourcePolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: AllowEventBridgeImageBuilderLogs
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "events.amazonaws.com"
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": "${ImageBuilderEventLogGroup.Arn}:*"
            }
          ]
        }



  CustomBuilderEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: ImageBuilderEventRule-3
      Description: Trigger AutoStopLambda when Image Builder AMI is AVAILABLE
      EventBusName: lamp-ec2-image
      State: ENABLED
      EventPattern:
        source:
          - custom.imagebuilder
        detail-type:
          - EC2 Image Builder Image State Change
        detail:
          state:
            status:
              - AVAILABLE
      Targets:
        - Id: AutoRefreshLambdaTarget
          Arn: !GetAtt AutoRefreshLambda.Arn

  CustomBuilderEventRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoRefreshLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CustomBuilderEventRule.Arn

  AutoRefreshLambdaPermission2:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoRefreshLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: arn:aws:events:eu-west-2:725673811658:rule/lamp-ec2-image/ImageBuilderEventRule-1



